{% set version = "3.4" %}
{% set posix = 'm2-' if win else '' %}

package:
  name: bison
  version: {{ version }}

source:
  url: http://ftp.gnu.org/gnu/bison/bison-{{ version }}.tar.gz
  sha256: ee1cc06f5e3d8615a5209cefaa2acd3da59b286d4d923cb6db5e6dbfae7a6c11

build:
  number: 1
  detect_binary_files_with_prefix: true

requirements:
  build:
    - perl
    - {{ compiler('c') }}           # [unix]
    - {{ compiler('cxx') }}         # [unix]
    - {{ compiler('m2w64_c') }}     # [win]
    - {{ compiler('m2w64_cxx') }}   # [win]
    - {{posix}}make
    - posix                         # [win]
    - {{posix}}autoconf
    - {{posix}}libtool
    - {{posix}}m4
    - m2-automake-wrapper           # [win]
    - m2-help2man                   # [win]
    - m2-texinfo                    # [win]
  host:
    - {{posix}}flex


test:
  commands:
    - yacc --help   # [unix]
    - bison --help

about:
  home: https://www.gnu.org/software/bison/
  license: GPL-3.0
  license_file: COPYING
  summary: General purpose parser generator converting annotated context-free grammar to a deterministic LR/GLR parser.
  description: |
    Bison is a general-purpose parser generator that converts an annotated
    context-free grammar into a deterministic LR or generalized LR (GLR) parser
    employing LALR(1) parser tables.
  dev_url: https://git.savannah.gnu.org/git/bison.git
  doc_url: http://savannah.gnu.org/projects/bison/

extra:
  recipe-maintainers:
    - jakirkham
    - mingwandroid
    - ocefpaf
